services:
  db:
    image: postgres:16-alpine
    container_name: flight_db
    environment:
      POSTGRES_DB: ${SQL_DATABASE}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: flight_redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flight_backend
    env_file:
      - .env
    environment:
      ENV_NAME: prod
      SQL_HOST: db
      SQL_PORT: 5432
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: flight_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  postgres_data:
