# Generated by Django 4.1.7 on 2026-03-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_alter_flight_flight_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
